$redis_user not redis_user !

diff --git a/redis/scripts/initialize b/redis/scripts/initialize
--- a/redis/scripts/initialize
+++ b/redis/scripts/initialize
@@ -4,7 +4,7 @@ set -o errtrace
 export PS4='+[${BASH_SOURCE}] : ${LINENO} : ${FUNCNAME[0]:+${FUNCNAME[0]}() $ }'
 
 log()  { printf "$*\n" ; return $? ;  }
-fail() { log "ERROR: $*" ; exit 1 ; }
+fail() { log "\nERROR: $*\n" ; exit 1 ; }
 
 if [[ ${debug_flag:-0} -eq 1 ]] ; then
   set -o verbose
