More nginx work.

diff --git a/nginx/bin/disable b/nginx/bin/disable
--- a/nginx/bin/disable
+++ b/nginx/bin/disable
@@ -1,6 +1,29 @@
 #!/usr/bin/env bash
 
 
-# Disable a 'server'
-# This renames /etc/nginx/servers/X.conf to X.conf.disabled
+# Disable a project_name
 #
+# This renames /etc/nginx/project_names/X.conf to X.conf.disabled if it exists
+# and prings an informative message otherwise.
+#
+
+source "$extension_scripts_path/initialize"
+
+project_name="${1:-}"
+if [[ -z "$project_name" ]] ; then
+  printf "project_name must be specified for 'nginx project_name'\n"
+fi
+
+if [[ -f "$nginx_project_names_path/$project_name.conf" ]] ; then
+  mv "$nginx_project_names_path/$project_name.conf" \
+    "$nginx_project_names_path/$project_name.conf.disabled"
+  exit $?
+else
+  if [[ -f "$nginx_project_names_path/$project_name.conf.disabled" ]] ; then
+    printf "INFO: $project_name.conf is already disabled.\n"
+    exit 0
+  else
+    printf "INFO: Cannot disable, $project_name.conf does not exist.\n"
+    exit 1
+  fi
+fi
diff --git a/nginx/bin/enable b/nginx/bin/enable
--- a/nginx/bin/enable
+++ b/nginx/bin/enable
@@ -1,6 +1,26 @@
 #!/usr/bin/env bash
 
 
-# Enable a 'server'
-# This renames /etc/nginx/servers/X.conf.disabled to X.conf
+# Enable a project_name (project)
+# This renames /etc/nginx/project_names/X.conf.disabled to X.conf
 
+source "$extension_scripts_path/initialize"
+
+project_name="${1:-}"
+if [[ -z "$project_name" ]] ; then
+  printf "project_name must be specified for 'nginx project_name'\n"
+fi
+
+if [[ -f "$nginx_project_names_path/$project_name.conf.disbled" ]] ; then
+  mv "$nginx_project_names_path/$project_name.conf.disbled" \
+    "$nginx_project_names_path/$project_name.conf"
+  exit $?
+else
+  if [[ -f "$nginx_project_names_path/$project_name.conf" ]] ; then
+    printf "INFO: $project_name.conf is already enabled.\n"
+    exit 0
+  else
+    printf "INFO: Cannot disable, $project_name.conf, $project_name.conf.disabled does not exist.\n"
+    exit 1
+  fi
+fi
diff --git a/nginx/scripts/initialize b/nginx/scripts/initialize
--- a/nginx/scripts/initialize
+++ b/nginx/scripts/initialize
@@ -22,9 +22,23 @@ export PATH="/sbin:/usr/sbin:/usr/local/sbin:/opt/sbin:/opt/local:sbin:$PATH"
 
 master_pid="$(ps auxww |  awk '/[n]ginx: master/{print $2}' | head -n 1)"
 
-config_file="${config_file:-"/etc/nginx/nginx.conf"}"
+if [[ -d /etc/init.d ]] ; then
+  init_scripts_path=/etc/init.d
+elif [[ -d /etc/rc.d ]] ; then
+  init_scripts_path=/etc/rc.d
+else
+  printf "ERROR: Unknown init scripts directory (/etc/init.d or /etc/rc.d not found).\n"
+  exit 1
+fi
 
+nginx_install_path="/usr/local/nginx"
+nginx_config_file="${nginx_config_file:-"/etc/nginx/nginx.conf"}"
 nginx_path="/etc/nginx"
 nginx_config_path="$nginx_path/conf"
 nginx_servers_path="$nginx_path/servers"
+nginx_binary="/usr/sbin/nginx"
+nginx_pid_file="/var/run/nginx.pid"
+nginx_lock_file="/var/lock/nginx.lock"
+nginx_spool_path="/var/spool/nginx"
+nginx_log_path="/var/log/nginx"
 
